### ISSUE TITLE
Auto-number gets confused by digits after point

### ISSUE THREAD

**Issue by hackerb9** [dykstrom/basic-mode#14]
With auto-number turned on, pressing enter when there are digits at and after the cursor point, merges the newly created line number and the number after point. 

For example, given this file:
```BASIC
10 REM Copylefted (ↄ) 2022.
                      ^
20 REM All wrongs reversed.
```

Hitting enter while the cursor is flashing on the first digit of 2022 will result in this:
```BASIC                                                             
10 REM Copylefted (ↄ)                                                   
152022 .                                                             
       ^                                                             
20 REM All wrongs reversed.                                              
```      
It should have put a space before 2022, not after. And the point should be left on the first digit of 2022, not on the period.

**Comment by dykstrom** [comment]
Fixed in version 0.4.6.
