### ISSUE TITLE
Renumber does not work when basic-line-number-cols is 0

### ISSUE THREAD

**Issue by hackerb9** [dykstrom/basic-mode#33]
When basic-line-numbers-cols is 0, basic-renumber refuses to run, saying

```log
No room for numbers.  Please adjust ‘basic-line-number-cols’.
```

**Comment by dykstrom** [comment]
Yes, that is because renumbering really does not work when basic-line-number-cols is 0. Historically, line numbers were turned off when the variable was 0. Now, when that is not the case, there seems to be a problem with basic-format-line-number (at least).

**Comment by dykstrom** [comment]
Done
