### ISSUE TITLE
Which compiler should I install?

### ISSUE THREAD

**Issue by OrionRandD** [dykstrom/basic-mode#36]
Which is the best basic compiler for emacs?
I am on debian...
sudo apt install ???

**Comment by dykstrom** [comment]
It seems most people that use Emacs to edit BASIC code use some kind of old-home-computer-emulator to run the code. If you are not interested in that I would suggest trying [FreeBASIC](https://www.freebasic.net). It is available for Linux, but the installation procedure is somewhat more complicated than running "sudo apt install". FreeBASIC is backwards compatible with QuickBASIC 4.5, which is supported by basic-mode.
